
export interface InfoDocencia{
    id:string;
    categoria:string;
    dedicacion:string;
    estado:string;//nuevo
    lineaActual:string;//nuevo
    tipoDocente:string;//nuevo
    fechaVigencia:string;//nuevo
    resolucionVigente:string;//nuevo
    inicio_dictado:Date;
    fin_dictado:Date;
    semestre:string;
    modo_ingreso:string;
    departamento:string;
    lugar_dictado:string;
    pais_dictado:string;
    dias_extranjero:string;
    labor_administrativa:string;
    rol_anterior:string;
    comisiones:string;
    emision_carne:Date;
    prestamos:string;
    sanciones:string;
    observadap:string;
    historico:string;
    felicitacion:string;
    codigoDocente:string;
}